// Copyright (c) 2017 Intel Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"time"
)

// CCLogEntry represents a single log entry for any Clear Containers component.
// The two essential fields are "Source" and "Time".
//
// Additional (non-standard) fields are stored in "Data".
type CCLogEntry struct {
	Time  time.Time
	Pid   int
	Level string
	Msg   string

	// System component type and name that generated the log entry
	Source string
	Name   string

	// Used to store additional (non-standard) fields
	Data map[string]string
}

// LogEntry is the main type used by the tool. It encapsulates a CCLogEntry
// but also container additional fields generated by the program.
type LogEntry struct {
	// difference between this record and the previous one
	TimeDelta time.Duration

	// Name of the file this entry belongs to
	Filename string

	// Line number in Filename this entry refers to
	Line uint64

	CCLogEntry
}

type LogEntries []LogEntry

// Required by sort.Sort
func (e LogEntries) Len() int {
	return len(e)
}

// Required by sort.Sort
func (e LogEntries) Swap(i, j int) {
	e[i], e[j] = e[j], e[i]
}

// Required by sort.Sort. Allows time-based sorting.
func (e LogEntries) Less(i, j int) bool {
	return e[i].Time.Before(e[j].Time)
}
